---

- name: Create local user record
  user:
    state: "{{ item.active | default(true) | bool | ternary('present', 'absent') }}"
    system: no
    name: "{{ item.user }}"
    uid: "{{ item.uid }}"
    comment: "{{ item.name }}"
    createhome: no
    home: "{{ homedir }}/{{ item.user }}"
    generate_ssh_key: no
    ssh_key_comment: "{{ item.name }}"
  with_items: "{{ users }}"