os_manila_mount_ceph_version: pacific
os_manila_mount_pkgs_install: True
os_manila_mount_ceph_repo_base: https://download.ceph.com/rpm-{{os_manila_mount_ceph_version}}/el8/x86_64/
os_manila_mount_ceph_conf_path: "/etc/ceph"

#os_manila_mount_ceph_repo_base: https://download.ceph.com/rpm-{{os_manila_mount_ceph_version}}/el8/x86_64/ceph-{{ os_manila_mount_ceph_version }}/"
#os_manila_mount_ceph_repo_key: "https://download.ceph.com/keys/release.asc"

# ceph_mount_facts:
#   nopt:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/15071be0-2c8f-46be-ae0f-d2ecc0c89430
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   scratch:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/efea823b-b78a-46bb-9e37-6e4f10e59462
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   home:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/12aa91d9-5297-4c1d-a8f2-e1dde1f3e3dd
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   projects:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/572f375c-7b29-486f-8e12-aecbd3b4cfb4
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==


ACO_CEPH_MOUNT_DATA:
  - NAME: "home"
    STORAGE_SERVER: "softiron"
    CEPH_ID: "nrel"
    SRC: "{{SOFTIRON_SERVER_SOURCES}}:/volumes/_nogroup/12aa91d9-5297-4c1d-a8f2-e1dde1f3e3dd"
    PATH: "/home"
    FSTYPE: "ceph"
    OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.softiron.nopt.secret
    CEPH_SECRET: "AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA=="

  - NAME: "nopt"
    STORAGE_SERVER: "softiron"
    CEPH_ID: "nrel"
    SRC: "{{SOFTIRON_SERVER_SOURCES}}:/volumes/_nogroup/15071be0-2c8f-46be-ae0f-d2ecc0c89430"
    PATH: "/nopt"
    FSTYPE: "ceph"
    OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.softiron.nopt.secret
    CEPH_SECRET: "AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA=="

  - NAME: "projects"
    STORAGE_SERVER: "softiron"
    CEPH_ID: "nrel"
    SRC: "{{SOFTIRON_SERVER_SOURCES}}:/volumes/_nogroup/572f375c-7b29-486f-8e12-aecbd3b4cfb4"
    PATH: "/projects"
    FSTYPE: "ceph"
    OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.softiron.nopt.secret
    CEPH_SECRET: "AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA=="

  - NAME: "scratch"
    STORAGE_SERVER: "softiron"
    CEPH_ID: "nrel"
    SRC: "{{SOFTIRON_SERVER_SOURCES}}:/volumes/_nogroup/efea823b-b78a-46bb-9e37-6e4f10e59462"
    PATH: "/scratch"
    FSTYPE: "ceph"
    OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.softiron.nopt.secret
    CEPH_SECRET: "AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA=="



# FSTAB_ENTRIES:
#   - SRC: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789:/volumes/_nogroup/15071be0-2c8f-46be-ae0f-d2ecc0c89430
#     PATH: /nopt
#     FSTYPE: ceph
#     OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.nopt.secret

#   - SRC: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789:/volumes/_nogroup/efea823b-b78a-46bb-9e37-6e4f10e59462
#     PATH: /scratch
#     FSTYPE: ceph
#     OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.scratch.secret

#   - SRC: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789:/volumes/_nogroup/12aa91d9-5297-4c1d-a8f2-e1dde1f3e3dd
#     PATH: /home
#     FSTYPE: ceph
#     OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.home.secret

#   - SRC: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789:/volumes/_nogroup/572f375c-7b29-486f-8e12-aecbd3b4cfb4
#     PATH: /projects
#     FSTYPE: ceph
#     OPTS: _netdev,noatime,name=nrel,secretfile=/etc/ceph/ceph.client.nrel.projects.secret

