---
# These may no longer be needed

# secrets_os_manila_mount_facts:
#   nopt:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/15071be0-2c8f-46be-ae0f-d2ecc0c89430
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   scratch:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/efea823b-b78a-46bb-9e37-6e4f10e59462
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   home:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/12aa91d9-5297-4c1d-a8f2-e1dde1f3e3dd
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==
#   projects:
#     host: 10.60.96.12:6789,10.60.96.13:6789,10.60.96.14:6789
#     export: /volumes/_nogroup/572f375c-7b29-486f-8e12-aecbd3b4cfb4
#     access_key: AQB5BZlgG8YINxAAlMih++WzNJuD8405pAjWrA==


