---
# Path to filebeat.yml configuration file template
filebeat_config_path: "{{ appliances_repository_root }}/environments/common/files/filebeat/filebeat.yml"

# User that runs the filebeat container
filebeat_podman_user: podman