opkssh_install_auth_cmd_user: opksshuser
opkssh_install_auth_cmd_group: opksshuser
opkssh_install_sudoers_path: /etc/sudoers.d/opkssh
opkssh_install_home_policy: true
opkssh_install_selinux_enable_proxy: false
opkssh_install_selinux_enable_squid: false
opkssh_install_restart_ssh: true
#opkssh_install_overwrite_active_config: false
opkssh_install_local_install_file:

opkssh_local_te_file:
opkssh_install_version: v0.13.0 # cannot be 'latest'

opkssh_install_dir: /usr/local/bin

opkssh_install_binary_name: opkssh
opkssh_install_github_repo: openpubkey/opkssh
opkssh_install_arch: amd64 # NB ansible_architecture is x86_64
opkssh_install_binary_url: "https://github.com/{{ opkssh_install_github_repo }}/releases/download/{{ opkssh_install_version }}/opkssh-linux-{{ opkssh_install_arch }}"

opkssh_disable_authorized_keys: true
opkssh_enable_authorized_keys_groups:
  - adm # includes 'rocky' user
opkssh_configure_hostbased_auth: true

opkssh_providers:
  google:
    issuer_uri: https://accounts.google.com
    client_id: 206584157355-7cbe4s640tvm7naoludob4ut1emii7sf.apps.googleusercontent.com
    expires: 24h
  microsoft:
    issuer_uri: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0
    client_id: 096ce0a3-5e72-4da8-9c86-12924b294a01
    expires: 24h
  gitlab:
    issuer_uri: https://gitlab.com
    client_id: 8d8b7024572c7fd501f64374dec6bba37096783dfcd792b3988104be08cb6923
    expires: 24h
  hello:
    issuer_uri: https://issuer.hello.coop
    client_id: app_xejobTKEsDNSRd5vofKB2iay_2rN
    expires: 24h

opkssh_auth_id: []
  # user:
  # opkssh_claim_selector: email, subject ID or group
  # [opkssh_provider]: 

opkssh_default_provider: "{{ opkssh_providers.keys() | first }}"
