---
# update_enable: false # Can uncomment for speed debugging non-update related build issues
sssd_install_ldap: true # include sssd-ldap package in fatimage
# update_enable: false # Can uncomment for speed debugging non-update related build issues

# NB: build will use Ark directly or via Pulp depending on what appliances_pulp_url is set to
# Ark password for pulp set in environments/.stackhpc/inventory/group_vars/all/pulp.yml
# because sync needs it
# Ark password for direct use set here, as the cluster should never have it:
dnf_repos_username: slurm-app-ci
dnf_repos_password: "{{ lookup('env','ARK_PASSWORD') }}"

# Open Ondemand osc.ood package installs - see ansible/roles/osc.ood/tasks/install-package.yml
install_ondemand_dex: true # install DEX
oidc_uri: '' # install mod_auth_openidc for OIDC
