openondemand_auth: basic_pam
openondemand_jupyter_partition: small
openondemand_desktop_partition: small
#openondemand_dashboard_support_url: 
#openondemand_dashboard_docs_url:
#openondemand_filesapp_paths:
