basic_users_users:
  - name: demo_user
    password: "{{ vault_demo_user_password | password_hash('sha512', 65534 | random(seed=inventory_hostname) | string) }}" # idempotent
    create_home: false
    uid: 1005
    sudo: demo_user ALL=(ALL) NOPASSWD:ALL

basic_users_homedir_server: "{{ groups['login'] | first }}"
basic_users_homedir_server_path: /home
