---

# Defaults to simplify job submission parameters
openhpc_config_extra:
  MpiDefault: pmix
  AccountingStorageEnforce: 'associations,limits,qos,safe'
  SelectTypeParameters: CR_Core_Memory
  GresTypes: gpu

openhpc_job_maxtime: '1-0'
