$ANSIBLE_VAULT;1.1;AES256
61313662666466633462333536323135373036366339363733396230353139323961613039663835
6564386437316439353431386365616634376435343934300a613936366566306363633862333139
33663362633938373736326337393862646261353062666662336566313436353263316662383735
6133643236636365620a313965353535303666316437373633643764626665633663393631336464
37366231353338666631656365333061623735336261373362386235666633623237656331386665
66616261343663616663383162623732373738306437656637626432373232623865373233656536
34313964623633653866613030633766386137623662356638386438633436393833646333326436
30623764643565636138
