---

- name: Get partition information
  shell: "sinfo --format %P --noheader"
  register: _sinfo_partitions
  changed_when: false

- name: Select default partition if hpctests_partition not given
  set_fact:
    hpctests_partition: "{{ (_sinfo_partitions.stdout_lines  | select('contains', '*') | first)[:-1] }}"
  when: hpctests_partition is not defined

- name: Get info about compute nodes
  shell: "sinfo --Node --noheader{%if hpctests_nodes is defined %} --nodes {{hpctests_nodes}}{% endif %} --partition {{hpctests_partition}} --format %N"
  register: hpctests_computes
  changed_when: false
  failed_when: hpctests_computes.rc != 0

- name: Check compute node selection valid
  assert:
    that: hpctests_computes.stdout_lines | length > 0
    fail_msg: "No nodes selected - was variable `hpctests_nodes` set (correctly)?"

- name: Create test root directory
  file:
    path: "{{ hpctests_rootdir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  become: true
