---
# Default to 10GB
cvmfs_quota_limit_mb: 10000

cvmfs_config_default:
  CVMFS_CLIENT_PROFILE: single
  CVMFS_QUOTA_LIMIT: "{{ cvmfs_quota_limit_mb }}"

cvmfs_config_overrides: {}
cvmfs_config: "{{ cvmfs_config_default | combine(cvmfs_config_overrides) }}"

cvmfs_gpg_checksum: "sha256:4ac81adff957565277cfa6a4a330cdc2ce5a8fdd73b8760d1a5a32bef71c4bd6"
