openhpc_partitions:
    - name: general
      default: YES
      partition_params:
        DefaultTime: 15
      nodegroups:
        - general-compute1
        - general-compute2
        - general-compute3
        - general-compute4
        - general-compute5
        - general-compute6
        - general-gen2-compute9
        - general-gen2-compute10
        - general-gen2-compute11
        - general-gen2-compute12
        - general-gen2-compute13
        # - general-gen2-compute14
        - general-gen2-compute15
        - general-gen2-compute16
        - general-gen2-compute17
        - general-gen2-compute18
        - general-gen2-compute19
        - general-gen2-compute20
        - general-gen2-compute21
        - general-gen2-compute22
        - general-gen2-compute23
        - general-gen2-compute24
        - general-gen2-compute25
        - general-gen2-compute26
        - general-gen2-compute27
        # - general-gen2-compute28
        - general-gen2-compute29
        - general-gen2-compute30
        - general-gen2-compute31
        - general-gen2-compute32
        - general-gen2-compute33
        - general-gen2-compute34
        - general-gen2-compute35
        - general-gen2-compute36
        - general-gen2-compute37
        - general-gen2-compute38
    - name: highmem
      default: NO
      partition_params:
        DefaultTime: 15
      nodegroups:
        - highmem-compute7
        - highmem-compute8
    - name: gpu
      default: NO
      partition_params:
        DefaultTime: 15
      nodegroups:
        - gpu-gpu1
        - gpu-gpu2
    - name: rebuild
      nodegroups:
        - general-compute1
        - general-compute2
        - general-compute3
        - general-compute4
        - general-compute5
        - general-compute6
        - highmem-compute7
        - highmem-compute8
        - gpu-gpu1
        - gpu-gpu2
        - general-gen2-compute9
        - general-gen2-compute10
        - general-gen2-compute11
        - general-gen2-compute12
        - general-gen2-compute13
        # - general-gen2-compute14
        - general-gen2-compute15
        - general-gen2-compute16
        - general-gen2-compute17
        - general-gen2-compute18
        - general-gen2-compute19
        - general-gen2-compute20
        - general-gen2-compute21
        - general-gen2-compute22
        - general-gen2-compute23
        - general-gen2-compute24
        - general-gen2-compute25
        - general-gen2-compute26
        - general-gen2-compute27
        # - general-gen2-compute28
        - general-gen2-compute29
        - general-gen2-compute30
        - general-gen2-compute31
        - general-gen2-compute32
        - general-gen2-compute33
        - general-gen2-compute34
        - general-gen2-compute35
        - general-gen2-compute36
        - general-gen2-compute37
        - general-gen2-compute38
      default: NO
      maxtime: 30
      partition_params:
        PriorityJobFactor: 65533
        Hidden: YES
        RootOnly: YES
        DisableRootJobs: NO
        PreemptMode: 'OFF'
        OverSubscribe: EXCLUSIVE
