openhpc_slurm_partitions:
    - name: general
    - name: highmem
    - name: gpu
    - name: rebuild
      groups:
        - name: general
        - name: highmem
        - name: gpu
      default: NO
      maxtime: 30
      partition_params:
        PriorityJobFactor: 65533
        Hidden: YES
        RootOnly: YES
        DisableRootJobs: NO
        PreemptMode: 'OFF'
        OverSubscribe: EXCLUSIVE
