mounts_tmp_size: '10%' # https://man7.org/linux/man-pages/man5/tmpfs.5.html
mounts_tmp_opts: "mode=1777,strictatime,nosuid,nodev,size={{ mounts_tmp_size }},nr_inodes=1m" # from tmp.mount unit
mounts_default:
  tmp:
    path: /tmp
    src: tmpfs
    fstype: tmpfs
    state: mounted
    opts: "{{ mounts_tmp_opts }}"
mounts_overrides: {}
mounts: "{{ mounts_default | combine(mounts_overrides) }}"
