autoscale_clouds: ~/.config/openstack/clouds.yaml

# recommended:
autoscale_show_suspended_nodes: true

# useful for debugging, may want to amend in production:
autoscale_debug_powersaving: true
autoscale_slurmctld_syslog_debug: info # https://slurm.schedmd.com/slurm.conf.html#OPT_SlurmctldSyslogDebug

# likely to need tuning:
autoscale_suspend_time: 120 # https://slurm.schedmd.com/slurm.conf.html#OPT_SuspendTime
autoscale_suspend_timeout: 30 # https://slurm.schedmd.com/slurm.conf.html#OPT_SuspendTimeout
autoscale_resume_timeout: 300 # https://slurm.schedmd.com/slurm.conf.html#OPT_ResumeTimeout
# autoscale_power_save_interval: 10 # https://slurm.schedmd.com/slurm.conf.html#OPT_power_save_interval
# autoscale_power_save_min_interval: 0 # https://slurm.schedmd.com/slurm.conf.html#OPT_power_save_min_intervals

# likely to need defining:
autoscale_suspend_exc_nodes: []

autoscale_openhpc_config:
  SuspendProgram: /opt/slurm-tools/bin/slurm-openstack-suspend
  ResumeProgram: /opt/slurm-tools/bin/slurm-openstack-resume
  SlurmctldParameters:
    - idle_on_node_suspend # https://slurm.schedmd.com/slurm.conf.html#OPT_idle_on_node_suspend
    - cloud_dns # https://slurm.schedmd.com/slurm.conf.html#OPT_cloud_dns
    # - "power_save_interval={{ autoscale_power_save_interval}}" # seems to break if you set this
    # - "power_save_min_interval={{ autoscale_power_save_min_interval }}"
  CommunicationParameters:
    - NoAddrCache # https://slurm.schedmd.com/slurm.conf.html#OPT_NoAddrCache
  PrivateData: "{{ ['cloud'] if autoscale_show_suspended_nodes else [] }}"
  DebugFlags: "{{ ['PowerSave'] if autoscale_debug_powersaving else [] }}" # NB: Seems to have disappeared in latest Slurm
  SlurmctldSyslogDebug: "{{ autoscale_slurmctld_syslog_debug }}"
  SuspendTime: "{{ autoscale_suspend_time }}"
  SuspendTimeout: "{{ autoscale_suspend_timeout }}"
  ResumeTimeout: "{{ autoscale_resume_timeout }}"
  SuspendExcNodes: "{{ autoscale_suspend_exc_nodes | join(',') }}"
# See also TreeWidth but shouldn't needs setting with cloud_dns
