---

- name: Set osc.ood variables from this role's defaults if no overriding inventory var
  set_fact:
    "{{ item.key }}": "{{ lookup('vars', item.key, default=item.value) }}"
  loop: "{{ openondemand_osc_ood_defaults | dict2items }}"
  when: (item.key in hostvars[inventory_hostname]) or (item.value)

# if using PAM auth we need apache installed but NOT started so split the osc.ood role up:
- include_role:
    name: osc.ood
    tasks_from: install-package.yml
    vars_from: Rocky.yml
    public: yes # Expose the vars from this role to the rest of the play
  # can't set vars: from a dict hence the workaround above

- include_tasks:
    file: pam_auth.yml
  when: openondemand_auth | lower == 'basic_pam'

- include_tasks:
    file: config_changes.yml

# The configure.yml playbook needs vars from Rocky (for nginx) and main if using OIDC auth. However vars_from doensn't take a list.
# include_vars doens't interpolate from role vars, so we use that for main.yml which only requires things we override in the appliance inventory
# and use vars_from for Rocky which requires interpolation from role vars.
#- include_vars:
#    file: roles/osc.ood/vars/main.yml

- include_role:
    name: osc.ood
    tasks_from: configure.yml
    vars_from: main.yml
    public: yes

- include_role:
    name: osc.ood
    tasks_from: install-apps.yml
  when: ood_install_apps

- include_role:
    name: osc.ood
    tasks_from: apps.yml
    # vars_from: Rocky.yml
  when: ood_apps

- name: Ensure post_tasks dirs exists
  file:
    path: "{{ item }}"
    state: directory
  loop:
    # - /etc/ood/config/apps/dashboard/initializers
    - /etc/ood/config/locales
    - /etc/ood/config/announcements.d
    - /etc/ood/config/pun/html

- name: Create dashboard additional config directory
  file:
    path: /etc/ood/config/apps/dashboard/initializers
    state: directory
    recurse: yes
    owner: root
    mode: o=rwX,go=rX

- name: Create additional shortcuts in Files app
  template:
    src: files_shortcuts.rb.j2
    dest: /etc/ood/config/apps/dashboard/initializers/ood.rb
    owner: root
    mode: o=rw,go=r
  when: openondemand_filesapp_paths

- name: Create job template directory
  file:
    path: "/etc/ood/config/apps/myjobs/templates/"
    state: directory
    recurse: True
    owner: root
    group: root
    mode: o=rwX,go=rX

- name: Copy web page to let users create their home directory
  copy:
    src: missing_home_directory.html
    dest: /etc/ood/config/pun/html/missing_home_directory.html

- name: Create mapping directory
  file:
    path: /etc/grid-security
    state: directory
    owner: root
    group: apache
    mode: u=rwX,g=rX,o=
  when: openondemand_mapping_users

- name: Create mapping file
  template:
    dest: /etc/grid-security/grid-mapfile
    src: grid-mapfile.j2
    owner: root
    group: apache
    mode: u=rw,g=r,o=
  when: openondemand_mapping_users

- name: Create app directories for dashboard links
  file:
    path: /var/www/ood/apps/sys/{{ item.app_name | default(item.name) }}
    state: directory
  loop: "{{ openondemand_dashboard_links }}"

- name: Create app manifests for dashboard links
  template:
    src: dashboard_app_links.yml.j2
    dest: /var/www/ood/apps/sys/{{ item.app_name | default(item.name) }}/manifest.yml
  loop: "{{ openondemand_dashboard_links }}"

# - name: Ensure ondemand-dex is running and active
#   service:
#     name: ondemand-dex
#     enabled: yes
#     state: stopped
#   when: false

# - name: Copy site images
#   copy:
#     src: ansible/roles/openondemand/ondemand
#     dest: "{{ item }}"
#   loop:
#     - /var/www/ood/public
#     - /usr/share/ondemand-dex/web/themes/
