# This is a clouds.yaml file, which can be used by OpenStack tools as a source
# of configuration on how to connect to a cloud. If this is your only cloud,
# just put this file in ~/.config/openstack/clouds.yaml and tools like
# python-openstackclient will just work with no further config. (You will need
# to add your password to the auth section)
# If you have more than one cloud account, add the cloud entry to the clouds
# section of your existing file and you can refer to them by name with
# OS_CLOUD=openstack or --os-cloud=openstack
clouds:
  openstack:

    auth:

      auth_url: https://vs-api.hpc.nrel.gov:5000

      application_credential_id: "a73d2c4685da426e8e9651a2727a5d46"
      application_credential_secret: "fKcgELm_IStZk4YCXKN5N709CjI5IRU2SgKI58G4DvPJRY6q--wadGGX8vdWGSbAJ9A0vhfQ2hVLNjg559i0SA"



    region_name: "RegionOne"


    interface: "public"
    identity_api_version: 3
    auth_type: "v3applicationcredential"


