---
- name: Test ansible-init has worked
  hosts: localhost
  tasks:
- name: check if mount directory exists
  stat:
    path: "{{ item.get('nfs_client_mnt_point', nfs_client_mnt_point) }}"
  register: _nfs_mountpoint
  failed_when: false
- name: unmount stale nfs mount
  mount:
    path: "{{ item.get('nfs_client_mnt_point', nfs_client_mnt_point) }}"
    state: unmounted
  when: "'Stale file handle' in _nfs_mountpoint.msg | default('')"
- name: ensure mount directory exists
  file:
    path: "{{ item.get('nfs_client_mnt_point', nfs_client_mnt_point) }}"
    state: directory
- name: mount the filesystem
  mount:
    path: "{{ item.get('nfs_client_mnt_point', nfs_client_mnt_point) }}"
    src: "{{ item.get('nfs_server', nfs_server) }}:{{ item.get('nfs_export', nfs_export) }}"
    opts: "{{ item['nfs_client_mnt_options'] | default(nfs_client_mnt_options, true) | default(omit, true) }}" # for some reason items.get() here fails with "an incorrect mount option was specified"
    fstype: nfs
    state: "{{ item.get('nfs_client_mnt_state', nfs_client_mnt_state) }}"
