---
- hosts: cluster
  become: true
  tasks:
    - name: Enable service tmp.mount and ensure it is not masked
      ansible.builtin.systemd:
        name: tmp.mount
        enabled: true
        masked: no

    - name: Start service tmp.mount
      ansible.builtin.systemd:
        name: tmp.mount
        state: started
