---

- hosts: cluster
  gather_facts: false
  become: false
  tasks:
    - name: Lock/Unlock instances
      openstack.cloud.server_action:
        action: "{{ appliances_server_action | default('lock') }}"
        server: "{{ inventory_hostname }}"
      delegate_to: localhost