---

- hosts: cluster
  gather_facts: no
  become: no
  tasks:
    - name: Lock/Unlock instances
      openstack.cloud.server_action:
        action: "{{ appliances_server_action | default('lock') }}"
        server: "{{ inventory_hostname }}"
      delegate_to: localhost