---

- hosts: "{{ target_hosts | default('all') }}"
  gather_facts: no
  become: no
  tasks:
    - name: Lock/Unlock instances
      openstack.cloud.server_action:
        action: "{{ server_action | default('lock') }}"
        server: "{{ inventory_hostname }}"