---
- hosts: pulp_server
  tasks:
    - ansible.builtin.include_role:
        name: pulp_site
        tasks_from: sync.yml
      vars:
        # default distribution to *latest* specified for baseos repo:
        pulp_site_target_distribution_version: "{{ dnf_repos_repos['baseos'].keys() | map('float') | sort | last }}"
