openhpc_partitions:
    - name: general-gen2
      nodegroups:
        - general-gen2-rack6
      partition_params:
        DefaultTime: 15
    - name: rebuild
      nodegroups:
        - general-gen2-rack6
      default: NO
      maxtime: 30
      partition_params:
        PriorityJobFactor: 65533
        Hidden: YES
        RootOnly: YES
        DisableRootJobs: NO
        PreemptMode: 'OFF'
        OverSubscribe: EXCLUSIVE
