
name: Test on Arcus OpenStack in rcp-cloud-portal-demo
on:
  push:
    branches:
      - main
  pull_request:
concurrency: rcp-cloud-portal_demo # openstack project
jobs:
  arcus:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup ssh
        run: |
          set -x
          mkdir ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 0600 ~/.ssh/id_rsa
        env:
          SSH_KEY: ${{ secrets.ARCUS_SSH_KEY }}

      - name: Add bastion's ssh key to known_hosts
        run: cat environments/arcus/bastion_fingerprint >> ~/.ssh/known_hosts
        shell: bash
      
      - name: Install ansible etc
        run: dev/setup-env.sh

      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
      
      - name: Initialise terraform
        run: terraform init
        working-directory: ${{ github.workspace }}/environments/arcus/terraform
        
      - name: Write clouds.yaml
        run: |
          mkdir -p ~/.config/openstack/
          echo "$CLOUDS_YAML" > ~/.config/openstack/clouds.yaml
        shell: bash
        env:
          CLOUDS_YAML: ${{ secrets.ARCUS_CLOUDS_YAML }}
      
      - name: Provision infrastructure
        id: provision
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          cd $APPLIANCES_ENVIRONMENT_ROOT/terraform
          terraform apply -auto-approve
        env:
          OS_CLOUD: openstack
          TF_VAR_cluster_name: ci${{ github.run_id }}
      
      - name: Get server provisioning failure messages
        id: provision_failure
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          cd $APPLIANCES_ENVIRONMENT_ROOT/terraform
          echo "::set-output name=messages::$(./getfaults.py)"
        env:
          OS_CLOUD: openstack
          TF_VAR_cluster_name: ci${{ github.run_id }}
        if: always() && steps.provision.outcome == 'failure'
        
      - name: Delete infrastructure if failed due to lack of hosts
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          cd $APPLIANCES_ENVIRONMENT_ROOT/terraform
          terraform destroy -auto-approve
        env:
          OS_CLOUD: openstack
          TF_VAR_cluster_name: ci${{ github.run_id }}
        if: ${{ always() && steps.provision.outcome == 'failure' && contains('not enough hosts available', steps.provision_failure.messages) }}

      - name: Directly configure cluster and build compute + login images
        # see pre-hook for the image build
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible all -m wait_for_connection
          ansible-playbook ansible/adhoc/generate-passwords.yml
          ansible-playbook -vv ansible/site.yml
        env:
          OS_CLOUD: openstack
          ANSIBLE_FORCE_COLOR: True
      
      - name: Test reimage of login and compute nodes
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible all -m wait_for_connection
          ansible-playbook -vv $APPLIANCES_ENVIRONMENT_ROOT/ci/test_reimage.yml
        env:
          OS_CLOUD: openstack
          ANSIBLE_FORCE_COLOR: True
      
      - name: Update cloud image and reconfigure Slurm
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible-playbook -vv $APPLIANCES_ENVIRONMENT_ROOT/ci/update_cloudnode_image.yml
          ansible-playbook -vv ansible/slurm.yml --tags openhpc --skip-tags install
        env:
          ANSIBLE_FORCE_COLOR: True
          OS_CLOUD: openstack
      
      - name: Run MPI-based tests (triggers autoscaling)
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible-playbook -vv ansible/adhoc/hpctests.yml
        env:
          ANSIBLE_FORCE_COLOR: True

      - name: Wait for CLOUD nodes to be destroyed
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible-playbook -vv $APPLIANCES_ENVIRONMENT_ROOT/ci/wait_for_scaledown.yml
        env:
          OS_CLOUD: openstack
          ANSIBLE_FORCE_COLOR: True

      - name: Delete infrastructure
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          cd $APPLIANCES_ENVIRONMENT_ROOT/terraform
          terraform destroy -auto-approve
        env:
          TF_VAR_cluster_name: ci${{ github.run_id }}
        if: ${{ success() || cancelled() }}

      - name: Delete images
        run: |
          . venv/bin/activate
          . environments/arcus/activate
          ansible-playbook -vv $APPLIANCES_ENVIRONMENT_ROOT/ci/delete_images.yml
        env:
          OS_CLOUD: openstack
          ANSIBLE_FORCE_COLOR: True
