
name: Upload release images to client sites from s3
on:
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        description: Image name from https://object.arcus.openstack.hpc.cam.ac.uk/swift/v1/AUTH_3a06571936a0424bb40bc5c672c4ccb1/openhpc-images/
        required: true

  # push:
  #   branches:
  #     - main
  #     - master
  #     - feat/fatimage-auto-upload

jobs:
  image_upload:
    runs-on: ubuntu-22.04
    concurrency: ${{ github.ref }}
    env: 
      OS_CLOUD: openstack
      IMAGE_LIST: "RL8 RL9"
    steps:
      - uses: actions/checkout@v4

      - name: Write clouds.yaml
        run: |
          mkdir -p ~/.config/openstack/
          echo "${{ secrets[format('{0}_CLOUDS_YAML', vars.CI_CLOUD)] }}" > ~/.config/openstack/clouds.yaml
        shell: bash

      - name: Upload latest image if missing
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U pip
          pip install $(grep python-openstackclient requirements.txt)
          . environments/.stackhpc/activate
          bash .github/bin/get-s3-image.sh ${{ inputs.image_name }}