
name: Test vagrant with ansible
on:
  push:
  pull_request:
jobs:
  vagrant-example:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Install coreutils (for realpath on osx)
        run: brew install coreutils

      - name: Add coreutils to path
        run: echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup environment
        run: dev/setup-env.sh

      - name: Provision infrastructure
        run: dev/vagrant-example-provision.sh

      - name: Configure infrastructure
        run: dev/vagrant-example-configure.sh
        env:
          ANSIBLE_FORCE_COLOR: True
      
      - name: Run MPI-based tests
        run: dev/vagrant-example-hpctests.sh
        env:
          ANSIBLE_FORCE_COLOR: True
