
name: Test vagrant with ansible
on: [push]
jobs:
  vagrant-example:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install coreutils (for realpath on osx)
        run: sudo brew install coreutils

      - name: Add coreutils to path
        run: echo "/usr/local/opt/coreutils/libexec/gnubin" >> $GITHUB_PATH

      - name: Setup environment
        run: dev/setup-env.sh

      - name: Provision infrastructure
        run: dev/vagrant-example-provision.sh

      - name: Configure infrastructure
        run: dev/vagrant-example-configure.sh